export const FIREBASE_MODEL_VERSION = 2;

export const FIREBASE_COLLECTIONS = {
  users: "users",
  workouts: "workouts",
  programs: "programs",
  exercises: "exercises",
  recipes: "recipes",
  subscriptions: "subscriptions",
  progress: "progress",
  workoutSessions: "workoutSessions",
  communityPosts: "communityPosts",
  comments: "comments",
  notifications: "notifications",
  mediaAssets: "mediaAssets",
  reports: "reports",
  moderationActions: "moderationActions",
  coachAssignments: "coachAssignments",
  adminAuditLogs: "adminAuditLogs",
  appSettings: "appSettings",
  appNavigation: "appNavigation",
  homeContent: "homeContent",
  analyticsEvents: "analyticsEvents",
  analyticsUserRegisteredEvents: "analyticsUserRegisteredEvents",
  analyticsSubscriptionStartedEvents: "analyticsSubscriptionStartedEvents",
  analyticsWorkoutStartedEvents: "analyticsWorkoutStartedEvents",
  analyticsWorkoutCompletedEvents: "analyticsWorkoutCompletedEvents",
  analyticsProgramOpenedEvents: "analyticsProgramOpenedEvents",
  analyticsCommunityPostCreatedEvents: "analyticsCommunityPostCreatedEvents",

  appContent: "appContent",
  communityMessages: "communityMessages",
  userPrograms: "userPrograms",
  userSubscriptions: "userSubscriptions",
  profiles: "profiles",
};

export const FIREBASE_DOCUMENTS = {
  appContentRoot: "sanctuary",
  mainSettings: "main",
};

export const FIREBASE_SUBCOLLECTIONS = {
  userProfile: "profile",
  userProgress: "progress",
  messageLikes: "likes",
  messageReactions: "reactions",
};

export const FIREBASE_CONTENT_STATUSES = {
  draft: "draft",
  published: "published",
  archived: "archived",
};

export const FIREBASE_MODERATION_STATES = {
  visible: "visible",
  pendingReview: "pendingReview",
  approved: "approved",
  hidden: "hidden",
  removed: "removed",
  blocked: "blocked",
};

export const FIREBASE_ACCESS_FIELDS = {
  freeTierAccessible: "boolean",
  subscriptionRequired: "boolean",
  requiredSubscriptionTier: "string",
  visibility: "public | authenticated | subscriber | ownerOnly",
};

export const FIREBASE_PERMISSIONS = {
  manageAllContent: "manage:allContent",
  managePrograms: "manage:programs",
  manageWorkouts: "manage:workouts",
  manageExercises: "manage:exercises",
  manageRecipes: "manage:recipes",
  manageUsers: "manage:users",
  manageSubscriptions: "manage:subscriptions",
  moderateCommunity: "moderate:community",
  reviewReports: "review:reports",
  viewAdminDashboard: "view:adminDashboard",
  viewAssignedUsers: "view:assignedUsers",
  manageAssignedProgress: "manage:assignedProgress",
  createCommunityPosts: "create:communityPosts",
  createAmbassadorPosts: "create:ambassadorPosts",
  accessBetaFeatures: "access:betaFeatures",
  submitBetaFeedback: "submit:betaFeedback",
  createReports: "create:reports",
  manageMedia: "manage:media",
  manageAppSettings: "manage:appSettings",
  viewAuditLogs: "view:auditLogs",
  useApp: "use:app",
};

export const FIREBASE_ROLES = {
  owner: {
    name: "Owner",
    scope: "Full business and platform control.",
    customClaim: "owner",
    permissions: [
      FIREBASE_PERMISSIONS.manageAllContent,
      FIREBASE_PERMISSIONS.managePrograms,
      FIREBASE_PERMISSIONS.manageWorkouts,
      FIREBASE_PERMISSIONS.manageExercises,
      FIREBASE_PERMISSIONS.manageRecipes,
      FIREBASE_PERMISSIONS.manageUsers,
      FIREBASE_PERMISSIONS.manageSubscriptions,
      FIREBASE_PERMISSIONS.manageMedia,
      FIREBASE_PERMISSIONS.manageAppSettings,
      FIREBASE_PERMISSIONS.moderateCommunity,
      FIREBASE_PERMISSIONS.reviewReports,
      FIREBASE_PERMISSIONS.viewAdminDashboard,
      FIREBASE_PERMISSIONS.viewAuditLogs,
      FIREBASE_PERMISSIONS.useApp,
    ],
  },
  admin: {
    name: "Admin",
    scope: "Operational admin for content, community, users, and subscriptions.",
    customClaim: "admin",
    permissions: [
      FIREBASE_PERMISSIONS.managePrograms,
      FIREBASE_PERMISSIONS.manageWorkouts,
      FIREBASE_PERMISSIONS.manageExercises,
      FIREBASE_PERMISSIONS.manageRecipes,
      FIREBASE_PERMISSIONS.manageUsers,
      FIREBASE_PERMISSIONS.manageSubscriptions,
      FIREBASE_PERMISSIONS.manageMedia,
      FIREBASE_PERMISSIONS.manageAppSettings,
      FIREBASE_PERMISSIONS.moderateCommunity,
      FIREBASE_PERMISSIONS.reviewReports,
      FIREBASE_PERMISSIONS.viewAdminDashboard,
      FIREBASE_PERMISSIONS.viewAuditLogs,
      FIREBASE_PERMISSIONS.useApp,
    ],
  },
  coach: {
    name: "Coach",
    scope: "Coaching access for assigned users and progress review.",
    customClaim: "coach",
    permissions: [
      FIREBASE_PERMISSIONS.viewAssignedUsers,
      FIREBASE_PERMISSIONS.manageAssignedProgress,
      FIREBASE_PERMISSIONS.createCommunityPosts,
      FIREBASE_PERMISSIONS.createReports,
      FIREBASE_PERMISSIONS.useApp,
    ],
  },
  user: {
    name: "User",
    scope: "Standard app user with subscription-based content access.",
    customClaim: "user",
    permissions: [FIREBASE_PERMISSIONS.createCommunityPosts, FIREBASE_PERMISSIONS.createReports, FIREBASE_PERMISSIONS.useApp],
  },
  betaTester: {
    name: "Beta Tester",
    scope: "Standard user plus early feature access and feedback.",
    customClaim: "betaTester",
    permissions: [
      FIREBASE_PERMISSIONS.createCommunityPosts,
      FIREBASE_PERMISSIONS.createReports,
      FIREBASE_PERMISSIONS.accessBetaFeatures,
      FIREBASE_PERMISSIONS.submitBetaFeedback,
      FIREBASE_PERMISSIONS.useApp,
    ],
  },
  ambassador: {
    name: "Ambassador",
    scope: "Community-facing user who can publish ambassador content.",
    customClaim: "ambassador",
    permissions: [
      FIREBASE_PERMISSIONS.createCommunityPosts,
      FIREBASE_PERMISSIONS.createAmbassadorPosts,
      FIREBASE_PERMISSIONS.createReports,
      FIREBASE_PERMISSIONS.useApp,
    ],
  },
};

export const FIREBASE_ROLE_IDS = Object.keys(FIREBASE_ROLES);

export const FIREBASE_ANALYTICS_EVENTS = {
  userRegistered: {
    eventName: "user_registered",
    collection: FIREBASE_COLLECTIONS.analyticsUserRegisteredEvents,
    scope: "auth",
    fields: {
      registrationMethod: "email | google | apple | manual",
      role: "string",
      subscriptionTier: "string",
    },
  },
  subscriptionStarted: {
    eventName: "subscription_started",
    collection: FIREBASE_COLLECTIONS.analyticsSubscriptionStartedEvents,
    scope: "subscription",
    fields: {
      subscriptionId: "string",
      provider: "manual | stripe | app_store | play_store",
      tier: "string",
      plan: "string",
      price: "number",
      currency: "string",
    },
  },
  workoutStarted: {
    eventName: "workout_started",
    collection: FIREBASE_COLLECTIONS.analyticsWorkoutStartedEvents,
    scope: "training",
    fields: {
      workoutId: "string",
      programId: "string",
      week: "number",
      day: "number",
    },
  },
  workoutCompleted: {
    eventName: "workout_completed",
    collection: FIREBASE_COLLECTIONS.analyticsWorkoutCompletedEvents,
    scope: "training",
    fields: {
      workoutId: "string",
      programId: "string",
      durationSeconds: "number",
      completionPercent: "number",
    },
  },
  programOpened: {
    eventName: "program_opened",
    collection: FIREBASE_COLLECTIONS.analyticsProgramOpenedEvents,
    scope: "content",
    fields: {
      programId: "string",
      programTitle: "string",
      freeTierAccessible: "boolean",
      subscriptionRequired: "boolean",
      requiredSubscriptionTier: "string",
    },
  },
  communityPostCreated: {
    eventName: "community_post_created",
    collection: FIREBASE_COLLECTIONS.analyticsCommunityPostCreatedEvents,
    scope: "community",
    fields: {
      postId: "string",
      contentType: "globalChatMessage | recipeShare | progressShare",
      attachmentCount: "number",
      hasText: "boolean",
    },
  },
};

export const FIREBASE_ANALYTICS_EVENT_NAMES = Object.values(FIREBASE_ANALYTICS_EVENTS).map((event) => event.eventName);

export const FIREBASE_MODEL_FIELDS = {
  User: {
    collection: FIREBASE_COLLECTIONS.users,
    id: "Firebase Auth uid",
    fields: {
      uid: "string",
      email: "string",
      displayName: "string",
      photoURL: "string",
      role: FIREBASE_ROLE_IDS.join(" | "),
      permissions: "string[] derived from role; custom claims remain authoritative for rules",
      status: "active | disabled | deleted",
      subscriptionTier: "string",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
    subcollections: {
      profile: "users/{uid}/profile/main",
      progress: "users/{uid}/progress/{programId}",
      notifications: "notifications filtered by uid",
    },
  },
  Workout: {
    collection: FIREBASE_COLLECTIONS.workouts,
    id: "slug or generated id",
    fields: {
      title: "string",
      description: "string",
      programId: "string",
      week: "number",
      day: "number",
      order: "number",
      exerciseIds: "string[]",
      estimatedMinutes: "number",
      freeTierAccessible: FIREBASE_ACCESS_FIELDS.freeTierAccessible,
      subscriptionRequired: "boolean",
      requiredSubscriptionTier: "string",
      visibility: FIREBASE_ACCESS_FIELDS.visibility,
      status: "draft | published | archived",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  Program: {
    collection: FIREBASE_COLLECTIONS.programs,
    currentAppContentPath: "appContent/sanctuary/programs/{programId}",
    activeUserMirror: "userPrograms/{userProgramId}",
    id: "slug or generated id",
    fields: {
      title: "string",
      category: "string",
      weeks: "string",
      level: "string",
      description: "string",
      image: "string",
      workoutIds: "string[]",
      freeTierAccessible: FIREBASE_ACCESS_FIELDS.freeTierAccessible,
      subscriptionRequired: "boolean",
      requiredSubscriptionTier: "string",
      visibility: FIREBASE_ACCESS_FIELDS.visibility,
      status: "draft | published | archived",
      order: "number",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  Exercise: {
    collection: FIREBASE_COLLECTIONS.exercises,
    id: "slug or generated id",
    fields: {
      title: "string",
      description: "string",
      videoUrl: "string",
      image: "string",
      muscleGroups: "string[]",
      equipment: "string[]",
      instructions: "string[]",
      cues: "string[]",
      freeTierAccessible: FIREBASE_ACCESS_FIELDS.freeTierAccessible,
      subscriptionRequired: "boolean",
      requiredSubscriptionTier: "string",
      visibility: FIREBASE_ACCESS_FIELDS.visibility,
      status: "draft | published | archived",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  Recipe: {
    collection: FIREBASE_COLLECTIONS.recipes,
    currentAppContentPath: "appContent/sanctuary/potions/{recipeId}",
    id: "slug or generated id",
    fields: {
      title: "string",
      category: "string",
      tab: "string",
      image: "string",
      timing: "string",
      ingredients: "string[]",
      preparation: "string",
      benefits: "string",
      freeTierAccessible: FIREBASE_ACCESS_FIELDS.freeTierAccessible,
      subscriptionRequired: "boolean",
      requiredSubscriptionTier: "string",
      visibility: FIREBASE_ACCESS_FIELDS.visibility,
      status: "draft | published | archived",
      order: "number",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  Subscription: {
    collection: FIREBASE_COLLECTIONS.subscriptions,
    userMirror: FIREBASE_COLLECTIONS.userSubscriptions,
    id: "uid or provider subscription id",
    fields: {
      uid: "string",
      email: "string",
      provider: "manual | stripe | app_store | play_store",
      providerSubscriptionId: "string",
      status: "active | trialing | past_due | canceled | expired",
      active: "boolean",
      tier: "string",
      plan: "string",
      startsAt: "Timestamp",
      endsAt: "Timestamp",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  WorkoutSession: {
    collection: FIREBASE_COLLECTIONS.workoutSessions,
    id: "generated id",
    fields: {
      uid: "string",
      programId: "string",
      workoutId: "string",
      status: "started | completed | abandoned",
      startedAt: "Timestamp",
      completedAt: "Timestamp",
      durationSeconds: "number",
      completionPercent: "number",
      source: "mobile | web | admin",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  Progress: {
    collection: FIREBASE_COLLECTIONS.progress,
    currentUserPath: "users/{uid}/progress/{programId}",
    id: "uid_programId or generated id",
    fields: {
      uid: "string",
      programId: "string",
      workoutId: "string",
      percent: "number",
      completedWorkouts: "number",
      totalWorkouts: "number",
      lastCompletedAt: "Timestamp",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  CommunityAttachment: {
    storage: "embedded on CommunityPost.attachments",
    fields: {
      id: "string",
      type: "image | recipe | progress | program",
      title: "string",
      image: "string",
      url: "string",
      storagePath: "string",
      recipeId: "string",
      programId: "string",
      progressPercent: "number",
      userName: "string",
      meta: "Record<string, unknown>",
    },
  },
  CommunityPost: {
    collection: FIREBASE_COLLECTIONS.communityPosts,
    currentChatCollection: FIREBASE_COLLECTIONS.communityMessages,
    id: "generated id",
    fields: {
      uid: "string",
      name: "string",
      email: "string",
      text: "string",
      attachments: "Attachment[]",
      visibility: "visible | hidden | removed | blocked",
      moderationStatus: "pendingReview | approved | hidden | blocked",
      reviewStatus: "pending | reviewed",
      reportCount: "number",
      reactionCounts: "Record<emoji, number>",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
    subcollections: {
      reactions: "communityMessages/{messageId}/reactions/{uid}",
      comments: "comments filtered by postId",
    },
  },
  Comment: {
    collection: FIREBASE_COLLECTIONS.comments,
    id: "generated id",
    fields: {
      postId: "string",
      parentCommentId: "string",
      uid: "string",
      name: "string",
      text: "string",
      visibility: "visible | hidden | removed | blocked",
      moderationStatus: "pendingReview | approved | hidden | blocked",
      reactionCounts: "Record<emoji, number>",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  MediaAsset: {
    collection: FIREBASE_COLLECTIONS.mediaAssets,
    id: "generated id",
    fields: {
      uid: "string",
      url: "string",
      storagePath: "string",
      fileName: "string",
      contentType: "string",
      sizeBytes: "number",
      usage: "communityAttachment | programImage | recipeImage | profileImage | appContent",
      ownerType: "user | app | admin",
      linkedCollection: "string",
      linkedDocumentId: "string",
      visibility: "public | authenticated | subscriber | ownerOnly",
      moderationStatus: "pendingReview | approved | hidden | blocked",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  Report: {
    collection: FIREBASE_COLLECTIONS.reports,
    id: "generated id",
    fields: {
      reporterUid: "string",
      targetType: "communityPost | comment | mediaAsset | user",
      targetId: "string",
      targetOwnerUid: "string",
      reason: "spam | abuse | inappropriate | privacy | other",
      details: "string",
      status: "open | reviewing | resolved | dismissed",
      resolution: "string",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  ModerationAction: {
    collection: FIREBASE_COLLECTIONS.moderationActions,
    id: "generated id",
    fields: {
      moderatorUid: "string",
      targetType: "communityPost | comment | mediaAsset | user | report",
      targetId: "string",
      action: "approve | hide | remove | block | restore | dismissReport",
      reason: "string",
      previousState: "string",
      nextState: "string",
      reportId: "string",
      createdAt: "Timestamp",
    },
  },
  CoachAssignment: {
    collection: FIREBASE_COLLECTIONS.coachAssignments,
    id: "coachUid_userUid or generated id",
    fields: {
      coachUid: "string",
      userUid: "string",
      status: "active | paused | ended",
      assignedAt: "Timestamp",
      endedAt: "Timestamp",
      notes: "string",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  AdminAuditLog: {
    collection: FIREBASE_COLLECTIONS.adminAuditLogs,
    id: "generated id",
    fields: {
      actorUid: "string",
      actorRole: FIREBASE_ROLE_IDS.join(" | "),
      action: "string",
      targetCollection: "string",
      targetId: "string",
      before: "Record<string, unknown>",
      after: "Record<string, unknown>",
      reason: "string",
      createdAt: "Timestamp",
    },
  },
  AppSettings: {
    collection: FIREBASE_COLLECTIONS.appSettings,
    currentAppContentPath: "appContent/sanctuary/settings/main",
    id: "main or generated id",
    fields: {
      trainingTabs: "string[]",
      communityTabs: "string[]",
      communityReactions: "CommunityReactionSettings",
      uploadModes: "UploadMode[]",
      profileStats: "ProfileStat[]",
      brandDiscount: "BrandDiscount",
      cache: "CacheSettings",
      status: "draft | published | archived",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  AppNavigation: {
    collection: FIREBASE_COLLECTIONS.appNavigation,
    currentAppContentPath: "appContent/sanctuary/navItems/{navItemId}",
    id: "nav key",
    fields: {
      key: "string",
      label: "string",
      icon: "string",
      screen: "string",
      order: "number",
      visibility: FIREBASE_ACCESS_FIELDS.visibility,
      status: "draft | published | archived",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  HomeContent: {
    collection: FIREBASE_COLLECTIONS.homeContent,
    currentAppContentPath: "appContent/sanctuary/settings/main",
    id: "main or generated id",
    fields: {
      dailyFocus: "string",
      todayTasks: "Task[]",
      dailyBoard: "DailyBoard",
      quickActions: "QuickAction[]",
      status: "draft | published | archived",
      createdAt: "Timestamp",
      updatedAt: "Timestamp",
    },
  },
  Notification: {
    collection: FIREBASE_COLLECTIONS.notifications,
    id: "generated id",
    fields: {
      uid: "string",
      type: "community_reaction | comment | subscription | program | system",
      title: "string",
      body: "string",
      deepLink: "string",
      read: "boolean",
      createdAt: "Timestamp",
      readAt: "Timestamp",
    },
  },
  AnalyticsEvent: {
    collection: FIREBASE_COLLECTIONS.analyticsEvents,
    eventCollections: Object.fromEntries(
      Object.entries(FIREBASE_ANALYTICS_EVENTS).map(([key, event]) => [key, event.collection]),
    ),
    id: "generated id",
    fields: {
      eventName: FIREBASE_ANALYTICS_EVENT_NAMES.join(" | "),
      uid: "string",
      email: "string",
      role: FIREBASE_ROLE_IDS.join(" | "),
      sessionId: "string",
      anonymousId: "string",
      source: "mobile | web | admin | server",
      platform: "ios | android | web",
      appVersion: "string",
      occurredAt: "Timestamp",
      createdAt: "Timestamp",
      context: "Record<string, unknown>",
      data: "Record<string, unknown>",
    },
  },
};

export const CURRENT_FIREBASE_USAGE = {
  appContent: {
    path: "appContent/sanctuary",
    usedFor: ["settings", "images", "programs", "potions", "navItems", "communityPosts"],
  },
  communityMessages: {
    path: "communityMessages/{messageId}",
    usedFor: ["global chat posts", "shared recipes", "shared progress", "reaction counts"],
  },
  messageReactions: {
    path: "communityMessages/{messageId}/reactions/{uid}",
    usedFor: ["current user reaction", "reaction audit trail"],
  },
  users: {
    path: "users/{uid}",
    usedFor: ["profile root", "subscription fallback", "per-user subcollections"],
  },
  userProfile: {
    path: "users/{uid}/profile/main",
    usedFor: ["editable app profile"],
  },
  userProgress: {
    path: "users/{uid}/progress/{programId}",
    usedFor: ["per-user program progress"],
  },
  userPrograms: {
    path: "userPrograms/{userProgramId}",
    usedFor: ["active programs available for progress sharing"],
  },
  subscriptions: {
    path: "subscriptions/{subscriptionId}",
    usedFor: ["global subscription lookup"],
  },
  userSubscriptions: {
    path: "userSubscriptions/{subscriptionId}",
    usedFor: ["per-user subscription lookup"],
  },
  appContentSettings: {
    path: "appContent/sanctuary/settings/main",
    usedFor: ["training tabs", "community tabs", "reaction settings", "home/profile/wellness configuration"],
  },
  appContentImages: {
    path: "appContent/sanctuary/images/{imageId}",
    usedFor: ["app-managed image urls"],
  },
  appContentPotions: {
    path: "appContent/sanctuary/potions/{recipeId}",
    usedFor: ["current recipe/wellness drink content"],
  },
  appContentNavItems: {
    path: "appContent/sanctuary/navItems/{navItemId}",
    usedFor: ["drawer and bottom navigation configuration"],
  },
  appContentCommunityPosts: {
    path: "appContent/sanctuary/communityPosts/{postId}",
    usedFor: ["seeded non-chat community cards"],
  },
  mediaAssets: {
    path: "mediaAssets/{mediaAssetId}",
    usedFor: ["uploaded or admin-managed media metadata"],
  },
  reports: {
    path: "reports/{reportId}",
    usedFor: ["user-created moderation reports"],
  },
  moderationActions: {
    path: "moderationActions/{moderationActionId}",
    usedFor: ["owner/admin moderation history"],
  },
  workoutSessions: {
    path: "workoutSessions/{workoutSessionId}",
    usedFor: ["workout start/completion history"],
  },
  coachAssignments: {
    path: "coachAssignments/{coachAssignmentId}",
    usedFor: ["coach-to-user relationships"],
  },
  adminAuditLogs: {
    path: "adminAuditLogs/{adminAuditLogId}",
    usedFor: ["owner/admin change history"],
  },
  analyticsEvents: {
    path: "analyticsEvents/{eventId}",
    usedFor: ["normalized owner analytics event ledger"],
  },
  analyticsEventCollections: {
    path: "analytics{EventName}Events/{eventId}",
    usedFor: ["event-specific analytics collections for simpler owner/admin queries"],
  },
};
